version: 1.0.{build}
image:
- Visual Studio 2019

    


      
init:
    - ps: pip3 install sphinx breathe exhale sphinx_rtd_theme
    - ps: choco install doxygen.install
    - ps: choco install graphviz


before_build:
#    - ps: $path = [System.Environment]::GetEnvironmentVariable('PATH','Machine')
#    - ps: $path = ($path.Split(';') | Where-Object { $_ -ne 'C:\Program Files\Git\usr\bin' }) -join ';'
#    - ps: $path += ";C:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\mingw32\bin"
#    - ps: $env:path = $path
    - ps: cmake  -G"Ninja" -Bbuild .

build_script:
- ps: cmake --build build 